<div class="modal fade" id="movimientos_registro_cobros{{ $admin_cobro->slug }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white py-2">
                <span class="modal-title text-uppercase small" id="staticBackdropLabel">DETALLE DE COBRO: {{$admin_cobro->nro_operacion}}</span>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="contenido">
                    <table class="mt-2 mb-3" style="width: 100%; font-size: 13px">
                        <thead class="bg-light">
                            <th class="text-uppercase border border-encabezado text-center py-1 fw-bold small" style=" width: 15%">operación</th>
                            <th class="text-uppercase border border-encabezado text-center py-1 fw-bold small" style=" width: 30%">Nombre o razón social</th>
                            <th class="text-uppercase border border-encabezado text-center py-1 fw-bold small" style=" width: 25%">Cuenta</th>
                            <th class="text-uppercase border border-encabezado text-center py-1 fw-bold small" style=" width: 15%">Medio Pago</th>
                            <th class="text-uppercase border border-encabezado text-center py-1 fw-bold small" style=" width: 15%">Fecha</th>
                        </thead>
                        <tbody class="bg-cuerpo">
                            
                            <tr>
                                <td class="text-uppercase border border-encabezado text-center py-2 fw-normal small">{{ $admin_cobro->nro_operacion }}</td>
                                <td class="text-uppercase border border-encabezado text-center py-2 fw-normal small">{{ $admin_cobro->cliente }}</td>
                                <td class="text-uppercase border border-encabezado text-center py-2 fw-normal small">{{ $admin_cobro->ingreso }}</td>
                                <td class="text-uppercase border border-encabezado text-center py-2 fw-normal small">{{ $admin_cobro->medio_pago }}</td>
                                <td class="text-uppercase border border-encabezado text-center py-2 fw-normal small">{{ $admin_cobro->created_at->format('d-m-Y') }}</td>
                            </tr>
                        </tbody>
                    </table>
            
                    <table class="w-100 mt-3" style="font-size: 13px;">
                        <thead class="bg-light">
                            <tr>
                                <th class="border border-encabezado py-1 text-uppercase small text-center" style="width: 5%">N°</th>
                                <th class="border border-encabezado py-1 text-uppercase small text-center" style="width: 35%">Concepto</th>
                                @if($admin_cobro->tipo_transaccion == 'ATENCION' || $admin_cobro->tipo_transaccion == 'MEDICAMENTOS' || $admin_cobro->tipo_transaccion == 'EAUXILIAR' )
                                    <th class="border border-encabezado py-1 text-uppercase small text-center" style="width: 15%">Total</th>
                                    <th class="border border-encabezado py-1 text-uppercase small text-center" style="width: 15%">Cobrado</th>
                                    <th class="border border-encabezado py-1 text-uppercase small text-center" style="width: 15%">Por cobrar</th>
                                    <th class="border border-encabezado py-1 text-uppercase small text-center" style="width: 15%">Recibido</th>
                                @else
                                    <th class="border border-encabezado py-1 text-uppercase small text-center" style="width: 10%">Valor</th>
                                    <th class="border border-encabezado py-1 text-uppercase small text-center" style="width: 10%">IGV</th>
                                    <th class="border border-encabezado py-1 text-uppercase small text-center" style="width: 10%">Cantidad</th>
                                    <th class="border border-encabezado py-1 text-uppercase small text-center" style="width: 30%">Observaciones</th>
                                @endif
                            </tr>
                        </thead>
                            <tbody>
                                @php
                                    $contador = 1;
                                    $detalle_cobro = App\Models\Detallecobro::where('cobro_id',$admin_cobro->id)->get();
                                @endphp
                                @foreach($detalle_cobro as $item)
                                    <tr class="text-uppercase">
                                        <td class="border-0 border-end border-start py-1 border-encabezado text-center">{{ $contador }}</td>
                                        <td class="border-0 border-end py-1 border-encabezado text-center">{{ $item->concepto }}</td>
                                        @if($admin_cobro->tipo_transaccion == 'ATENCION' || $admin_cobro->tipo_transaccion == 'MEDICAMENTOS' || $admin_cobro->tipo_transaccion == 'EAUXILIAR')
                                            <td class="border-0 border-end py-1 border-encabezado text-end pe-2">{{ number_format($item->total, 2, '.', ',') }}</td>
                                            <td class="border-0 border-end py-1 border-encabezado text-end pe-2">{{ number_format($item->cobrado, 2, '.', ',') }}</td>
                                            <td class="border-0 border-end py-1 border-encabezado text-end pe-2">{{ number_format($item->por_cobrar, 2, '.', ',') }}</td>
                                            <td class="border-0 border-end py-1 border-encabezado text-end pe-2">{{ number_format($item->monto_recibido, 2, '.', ',') }}</td>
                                        @else
                                            <td class="border-0 border-end py-1 border-encabezado text-end pe-2">{{ number_format($item->valor, 2, '.', ',') }}</td>
                                            <td class="border-0 border-end py-1 border-encabezado text-end pe-2">{{ $item->igv }}</td>
                                            <td class="border-0 border-end py-1 border-encabezado text-end pe-2">{{ number_format($item->cantidad, 2, '.', ',') }}</td>
                                            <td class="border-0 border-end py-1 border-encabezado text-center">{{ $item->observaciones == ''?'': $item->observaciones }}</td>
                                        @endif
                                    </tr> 
                                    @php
                                        $contador++;
                                    @endphp
                                @endforeach  
                                
                                @if($detalle_cobro->count() ==10)
                                @elseif($detalle_cobro->count() ==9)
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                @elseif($detalle_cobro->count() ==8)
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                @elseif($detalle_cobro->count() ==7)
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                @elseif($detalle_cobro->count() ==6)
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                @elseif($detalle_cobro->count() ==5)
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                @elseif($detalle_cobro->count() ==4)
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                @elseif($detalle_cobro->count() ==3)
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                @elseif($detalle_cobro->count() ==2)
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                @elseif($detalle_cobro->count() ==1)
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                    <tr><td class="py-1 border-0 border-end border-start border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td><td class="py-1 border-0 border-end border-encabezado"><span style="opacity: 0;">0</span></td></tr>
                                @endif 
                                <tr class="text-uppercase">
                                    <td colspan="6" class="border-0 border-top border-start border-end py-1 px-2 border-encabezado"> <b>SON:</b> {{ $formatter->toInvoice($admin_cobro->total_cobrado,2,'soles') }}</td>
                                </tr>  
                                @if($admin_cobro->tipo_transaccion == 'VENTA')
                                @else
                                    <tr class="text-uppercase">
                                        <td colspan="3" class="border-0 border-top border-end py-1 border-encabezado text-center"></td>
                                        <td colspan="2" class="border-0 border-top border-end border-bottom px-2 py-1 border-encabezado">
                                            SUBTOTAL 
                                        </td>
                                        <td class="border-0 border-top border-end border-bottom  py-1 border-encabezado text-end px-2">{{ number_format($admin_cobro->subtotal, 2, '.', ',') }}</td>
                                    </tr>
                                    <tr class="text-uppercase">
                                        <td colspan="3" class="border-0 border-end py-1 border-encabezado text-center"></td>
                                        <td colspan="2" class="border-0 border-top border-end border-bottom px-2 py-1 border-encabezado">
                                            IGV 
                                        </td>
                                        <td class="border-0 border-top border-end border-bottom  py-1 border-encabezado text-end px-2">{{ number_format($admin_cobro->subtotal*$admin_cobro->igv, 2, '.', ',') }}</td>
                                    </tr>
                                @endif                
                                <tr class="text-uppercase">
                                    <td colspan="3" class="border-0 @if($admin_cobro->tipo_transaccion == 'VENTA') border-top @endif border-end py-1 border-encabezado text-center fw-bold"></td>
                                    <td colspan="2" class="border-0 border-top border-end border-bottom px-2 py-1 border-encabezado fw-bold">
                                        TOTAL 
                                    </td>
                                    <td class="border-0 border-top border-end border-bottom  py-1 border-encabezado text-end px-2 fw-bold">{{ number_format($admin_cobro->total_cobrado, 2, '.', ',') }}</td>
                                </tr>
                            </tbody>
                    </table>
            
                    <div class="card bg-transparent border-encabezado mt-3 mb-2" style="font-size: 13px;">
                        <div class="card-body p-1">
                            <p class="fw-bold mb-1">Observaciones:</p>
                            <p>- {{$admin_cobro->descripcion?$admin_cobro->descripcion:'Sin observaciones'}}</p>
                        </div>
                    </div>
                    <p class="" style="font-size: 13px"><b>RESPONSABLE: </b>{{ $admin_cobro->registrado_por }}</p>
                </div>
            </div>
        </div>
    </div>
</div>